import { z } from "zod";

export const RISK_CODES = {
  NET_RISK_DHCP4_STATIC_IPV4: "NET_RISK_DHCP4_STATIC_IPV4",
  NET_RISK_DHCP6_STATIC_IPV6: "NET_RISK_DHCP6_STATIC_IPV6",
  NET_RISK_DHCP4_DEFAULT_ROUTE: "NET_RISK_DHCP4_DEFAULT_ROUTE",
  NET_RISK_DHCP6_DEFAULT_ROUTE: "NET_RISK_DHCP6_DEFAULT_ROUTE",
  NET_RISK_DHCP4_SPECIFIC_ROUTE: "NET_RISK_DHCP4_SPECIFIC_ROUTE",
  NET_RISK_DHCP6_SPECIFIC_ROUTE: "NET_RISK_DHCP6_SPECIFIC_ROUTE",
} as const;

export const RISK_CODE_SET = new Set<string>(Object.values(RISK_CODES));

export const riskCodeSchema = z.enum([
  RISK_CODES.NET_RISK_DHCP4_STATIC_IPV4,
  RISK_CODES.NET_RISK_DHCP6_STATIC_IPV6,
  RISK_CODES.NET_RISK_DHCP4_DEFAULT_ROUTE,
  RISK_CODES.NET_RISK_DHCP6_DEFAULT_ROUTE,
  RISK_CODES.NET_RISK_DHCP4_SPECIFIC_ROUTE,
  RISK_CODES.NET_RISK_DHCP6_SPECIFIC_ROUTE,
]);

export type RiskCode = z.infer<typeof riskCodeSchema>;

export const NETWORKING_STRUCTURAL_CODES = new Set<string>([
  "NET_DUP_TARGET",
  "NET_DUP_ADDRESS_SAME_INTERFACE",
  "NET_DUP_ADDRESS_CROSS_INTERFACE",
  "NET_ROUTE_FAMILY_MISMATCH",
  "NET_ROUTE_UNREACHABLE_FAMILY",
  "NET_DEFAULT_ROUTE_CONFLICT_SAME_INTERFACE",
  "NET_DEFAULT_ROUTE_CONFLICT_CROSS_INTERFACE",
]);

export const NETWORKING_CROSS_INTERFACE_CODES = new Set<string>([
  "NET_DUP_TARGET",
  "NET_DUP_ADDRESS_CROSS_INTERFACE",
  "NET_DEFAULT_ROUTE_CONFLICT_CROSS_INTERFACE",
]);
