export const NETWORKING_STRUCTURAL_CODES = new Set<string>([
  "NET_DUP_TARGET",
  "NET_DUP_ADDRESS_SAME_INTERFACE",
  "NET_DUP_ADDRESS_CROSS_INTERFACE",
  "NET_ROUTE_FAMILY_MISMATCH",
  "NET_ROUTE_UNREACHABLE_FAMILY",
  "NET_DEFAULT_ROUTE_CONFLICT_SAME_INTERFACE",
  "NET_DEFAULT_ROUTE_CONFLICT_CROSS_INTERFACE",
]);

export const NETWORKING_CROSS_INTERFACE_CODES = new Set<string>([
  "NET_DUP_TARGET",
  "NET_DUP_ADDRESS_CROSS_INTERFACE",
  "NET_DEFAULT_ROUTE_CONFLICT_CROSS_INTERFACE",
]);
